// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_patronizingly_easy_mode_door_count = "CgkInt6d-tsZEAIQCQ"; // <GPGSID>
        public const string leaderboard_highscore__omega_door = "CgkInt6d-tsZEAIQBA"; // <GPGSID>
        public const string leaderboard_highscore__door_dodger = "CgkInt6d-tsZEAIQEQ"; // <GPGSID>
        public const string leaderboard_highscore__ghost_mode = "CgkInt6d-tsZEAIQEA"; // <GPGSID>
        public const string leaderboard_highscore__blaster__mode = "CgkInt6d-tsZEAIQBg"; // <GPGSID>
        public const string leaderboard_highscore__powerup_mode = "CgkInt6d-tsZEAIQAQ"; // <GPGSID>
        public const string leaderboard_total_points_level_250 = "CgkInt6d-tsZEAIQCg"; // <GPGSID>
        public const string leaderboard_highscore__charge_mode = "CgkInt6d-tsZEAIQAg"; // <GPGSID>
        public const string leaderboard_highscore__door_buster = "CgkInt6d-tsZEAIQAw"; // <GPGSID>
        public const string leaderboard_highscore__double_doors = "CgkInt6d-tsZEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscore__standard = "CgkInt6d-tsZEAIQAA"; // <GPGSID>
        public const string leaderboard_ads_watched = "CgkInt6d-tsZEAIQDA"; // <GPGSID>

}

